FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY SensorApi.csproj .
RUN dotnet restore SensorApi.csproj
COPY . .
WORKDIR /src
RUN dotnet publish SensorApi.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS final
WORKDIR /app
COPY --from=build /app .
COPY wait-for-it/wait-for-it.sh wait-for-it.sh
RUN chmod a+x wait-for-it.sh
COPY docker/start_prod.sh start_prod.sh
RUN chmod a+x start_prod.sh
CMD ["bash", "start_prod.sh"]
