// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SensorApi.Models;
using System;

namespace SensorApi.Migrations
{
    [DbContext(typeof(TemperatureContext))]
    [Migration("20190303030911_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SensorApi.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PrimaryKey_DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SensorApi.Models.TemperatureItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DeviceId");

                    b.Property<double>("Temperature");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_TemperatureItemId");

                    b.HasIndex("DeviceId");

                    b.ToTable("TemperatureItems");
                });

            modelBuilder.Entity("SensorApi.Models.TemperatureItem", b =>
                {
                    b.HasOne("SensorApi.Models.Device", "Device")
                        .WithMany("TemperatureItems")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("ForeignKey_TemperatureItem_Device")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
